version: '3.1'

# Copy from here
# https://git.cepal.org/geo/geo-facility-geonetwork/-/blob/main/docker-compose.yml

# These steps to push image to ECR
# aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com
# docker tag IMAGE_ID 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/my-repository
# docker push 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/my-repository
#
# When running in dev env, you should uncomment build . instead of image from ECR

volumes:
  geonetwork4:

services:
  geonetwork:
    container_name: geonetwork4
    build: .
#    image: 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/raymond:latest
    restart: always
    environment:

#      JAVA_OPTS: >
#        -Xms256m -Xmx2g
#        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000

      ES_HOST: localhost
      ES_PROTOCOL: https
      ES_PORT: 9200
      ES_USERNAME: elastic
      ES_PASSWORD: open-sesame

      KB_URL: http://localhost:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: localhost
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: postgres
      GEONETWORK_DB_PASSWORD: password
#      GEONETWORK_DB_CONNECTION_PROPERTIES: readOnly=true

    network_mode: "host"
    volumes:
      - geonetwork4:/catalogue-data
