# GeoNetwork
#
# Access via "http://localhost:8080/geonetwork" (or "http://$(docker-machine ip):8080/geonetwork" if using docker-machine)
#
# Default user: admin
# Default password: admin

version: '3.7'
services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    networks:
      - elastic
    volumes:
      - ./elasticdata/certs:/usr/share/elasticsearch/config/certs
    user: "0"
    env_file:
      - .env
    command: >
      bash -c '        
        echo "Waiting for Elasticsearch availability";
        until curl -s http://es-container:9200 | grep -q "missing authentication credentials"; do echo "Waiting es-container up... "; sleep 2; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:open-sesame" -H "Content-Type: application/json" http://es-container:9200/_security/user/kibana_system/_password -d "{\"password\":\"password\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es-container/es-container.crt ]"]
      interval: 5s
      timeout: 5s
      retries: 120
      start_period: 20s

  es-container:
    container_name: es-container
    hostname: es-container
    depends_on:
      - setup
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 4GB
    restart: always
    user: "1000"
    volumes:
      - ./elasticdata/elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticdata/certs:/usr/share/elasticsearch/config/certs
    env_file:
      - .env
    environment:
      - ES_JAVA_OPTS=-Xms3g -Xmx4g
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
#      - xpack.security.http.ssl.enabled=false
#      - xpack.security.http.ssl.key=certs/es-container/es-container.key
#      - xpack.security.http.ssl.certificate=certs/es-container/es-container.crt
#      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
#      - xpack.security.http.ssl.verification_mode=certificate
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.transport.ssl.key=certs/es-container/es-container.key
#      - xpack.security.transport.ssl.certificate=certs/es-container/es-container.crt
#      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
#      - xpack.security.transport.ssl.verification_mode=certificate
      - discovery.type=single-node
      - ELASTIC_PASSWORD=open-sesame
    networks:
      elastic:
        ipv4_address: 10.5.0.5
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://es-container:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    container_name: kb-container
    hostname: kb-container
    image: docker.elastic.co/kibana/kibana:7.17.12
    restart: always
    user: "1000"
    env_file:
      - .env
    volumes:
      - ./elasticdata/certs:/usr/share/kibana/config/certs
      - ./elasticdata/kibana-data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=password
#      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ENTERPRISESEARCH_HOST=http://enterprise-search:3002
    depends_on:
      - setup
      - es-container
    networks:
      elastic:
        ipv4_address: 10.5.0.4
    ports:
      - 5601:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://kb-container:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  enterprisesearch:
    container_name: enterprise-search
    hostname: enterprise-search
    depends_on:
      - kibana
    env_file:
      - .env
    restart: always
    user: "1000"
    image: docker.elastic.co/enterprise-search/enterprise-search:7.17.12
    volumes:
      - ./elasticdata/certs:/usr/share/enterprise-search/config/certs
      - ./elasticdata/enterprisesearch-data:/usr/share/enterprise-search/data
    ports:
      - 3002:3002
    networks:
      elastic:
        ipv4_address: 10.5.0.3
    environment:
      - SERVERNAME=enterprise-search
      - secret_management.encryption_keys=["secret"]
      - allow_es_settings_modification=true
      - elasticsearch.host=http://es-container:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=open-sesame
#      - elasticsearch.ssl.enabled=false
#      - elasticsearch.ssl.certificate_authority=/usr/share/enterprise-search/config/certs/ca/ca.crt
      - kibana.external_url=http://kb-container:5601
      - ent_search.external_url=http://enterprise-search:3002
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://enterprise-search:3002 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  elasticdata:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1