version: '3.9'

# Copy from here
# https://git.cepal.org/geo/geo-facility-geonetwork/-/blob/main/docker-compose.yml

# These steps to push image to ECR
# aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com
# docker tag IMAGE_ID 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/my-repository
# docker push 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/my-repository
#
# When running in dev env, you should uncomment build . instead of image from ECR

# MAKE sure you create a folder call gn4_data before start to avoid permission issue
volumes:
  gn4_data:
    driver: local

services:
  geonetwork:
    container_name: geonetwork4
    build: .
    user: "root:root"
#    image: 615645230945.dkr.ecr.ap-southeast-2.amazonaws.com/raymond:latest
    restart: always
    volumes:
      # mapping for h2 db only
      - ./gn4_data:/var/lib/jetty/gn4data
      # data dir need to be persist across restart, the
      # -Dgeonetwork.data.dir -Dgeonetwork.config.dir argument is used to point and use this folder
      - ./gn4_data/data:/var/lib/jetty/data:rw
      - ./gn4_data/config:/var/lib/jetty/config:rw
    env_file:
      - .env
    environment:
      JAVA_OPTS: >-
        -Xms256m -Xmx2g 
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000  
        -Dgeonetwork.data.dir=/var/lib/jetty/data 
        -Dgeonetwork.config.dir=/var/lib/jetty/config 
        -Dgeonetwork.jeeves.configuration.overrides.file=/var/lib/jetty/webapps/geonetwork/WEB-INF/config-overrides.xml 

      ES_HOST: ${ES_HOST:-localhost}
      ES_PROTOCOL: ${ES_PROTOCOL:-https}
      ES_PORT: ${ES_PORT:-9200}
      ES_USERNAME: ${ES_USERNAME:-elastic}
      ES_PASSWORD: ${ES_PASSWORD:-open-sesame}

      KB_URL: ${KB_URL:-http://localhost:5601}

      INDEXER_HOST: ${INDEXER_HOST:-localhost}
      INDEXER_PORT: ${INDEXER_PORT:-8080}
      INDEXER_APIKEY: ${INDEXER_APIKEY}

      GEONETWORK_DB_TYPE: ${GEONETWORK_DB_TYPE:-h2}
      GEONETWORK_DB_HOST: ${GEONETWORK_DB_HOST:-localhost}
      GEONETWORK_DB_PORT: ${GEONETWORK_DB_PORT:-9001}
      GEONETWORK_DB_NAME: ${GEONETWORK_DB_NAME:-~/gn4data/geonetwork}
      GEONETWORK_DB_USERNAME: postgres
      GEONETWORK_DB_PASSWORD: password

      GEONETWORK_ROOTURL: ${GEONETWORK_HOST:-localhost}
      GEONETWORK_PROTOCOL: ${GEONETWORK_PROTOCOL:-http}
#      GEONETWORK_DB_CONNECTION_PROPERTIES: readOnly=true
    network_mode: "host"