aodn.geonetwork4.esIndexer.host=${INDEXER_HOST:}
aodn.geonetwork4.esIndexer.port=${INDEXER_PORT:80}
aodn.geonetwork4.esIndexer.apikey=${INDEXER_APIKEY}
aodn.geonetwork4.esIndexer.urlIndex=${aodn.geonetwork4.esIndexer.host}:${aodn.geonetwork4.esIndexer.port}/api/v1/indexer/index/{uuid}
# Written to GeoNetwork setting 'aodn/portalSync/enabled' on every start, change at runtime in Admin console > Settings > AODN Portal
aodn.geonetwork4.portalSync.enabledOnStart=false

management.info.env.enabled=true

# Actuator info point
info.application.name=@project.name@
info.application.description=@project.description@
info.application.version=@project.version@
